### ISSUE TITLE
Broken tags

### ISSUE THREAD

**Issue by stevetoro** [ElinaIvanova/The-Tea-Cozy_edu#2]
https://github.com/ElinaIvanova/The-Tea-Cozy_edu/blob/gh-pages/index.html#L6-L7

If your link tag is short enough, try to keep it on just a single line. Breaking it up into multiple lines increases the chance of the tag breaking due to some missing punctuation.

https://github.com/ElinaIvanova/The-Tea-Cozy_edu/blob/gh-pages/index.html#L12-L13

Don't forget to close your `ul` and `nav` tags. It's often a good idea to write your paired tags and then write the content inside those tags.

**Comment by ElinaIvanova** [comment]
Solved.
