### ISSUE TITLE
Image alt attributes

### ISSUE THREAD

**Issue by stevetoro** [ElinaIvanova/The-Tea-Cozy_edu#3]
https://github.com/ElinaIvanova/The-Tea-Cozy_edu/blob/gh-pages/index.html#L39
https://github.com/ElinaIvanova/The-Tea-Cozy_edu/blob/gh-pages/index.html#L43
https://github.com/ElinaIvanova/The-Tea-Cozy_edu/blob/gh-pages/index.html#L47

Great job adhering to the HTML5 standard of giving each image a descriptive alt attribute. This will make your website more accessible 🔥

**Comment by ElinaIvanova** [comment]
Thank you!
