### ISSUE TITLE
Class names

### ISSUE THREAD

**Issue by stevetoro** [ElinaIvanova/The-Tea-Cozy_edu#4]
https://github.com/ElinaIvanova/The-Tea-Cozy_edu/blob/gh-pages/index.html#L61-L81

Can you think of more descriptive class names than "boxes" or "box"? Remember, on the web, _everything is a box_.

**Comment by ElinaIvanova** [comment]
OK, I'm currently looking into BEM methodology. The next time I'll be more attentive to things like that. Practice makes perfect.
